### ISSUE TITLE
Ch 6 - adjust learning exercises

### ISSUE THREAD

**Issue by stewartadam** [charleszipp/abode#21]
After running through ch6, I found the [Integrating ADT with TSI](https://docs.microsoft.com/en-us/azure/digital-twins/how-to-integrate-time-series-insights) guide to the most informative and functional. Presently, the learning experience guides users to the [Getting started tutorial](https://docs.microsoft.com/en-us/azure/time-series-insights/tutorial-set-up-environment) and [ingesting data from event hub](https://docs.microsoft.com/en-us/azure/time-series-insights/how-to-ingest-data-event-hub) which is effectively what the first link does, but without ADT-specific guidance so users may end up using the wrong property name when creating TSI, etc and need to start over or have to manually setup the flow into the event hub.

I would recommend directly pointing users to the [Integrating ADT with TSI](https://docs.microsoft.com/en-us/azure/digital-twins/how-to-integrate-time-series-insights) page as a learning experience as it is more targeted and instructional.

**Comment by charleszipp** [comment]
@jackiebecker do you have any issues with switching the first learning exercise to direct to the tutorial @stewartadam suggested? It does appear to be a more e2e complete example. I think others within our group also found this article helpful if I am remembering correctly.

**Comment by jackiebecker** [comment]
No issue.

**Comment by jackiebecker** [comment]
Since the tutorial mentioned as helpful by @stewartadam is already linked, I am just going to remove the first Getting Started tutorial. The doc already states this is unnecessary, but agree it might be easier for happy path just to remove. LMK if that doesn't address your concern @stewartadam .

**Comment by stewartadam** [comment]
Sounds good, thanks!
